### ISSUE TITLE
NoMethodError

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hyrax#384]
```
     NoMethodError:
       undefined method `length' for nil:NilClass
     # /Users/jcoyne/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/bundler/gems/hyrax-d5091b53bb71/app/services/hyrax/admin_set_service.rb:77:in `block (2 levels) in count_files'
     # /Users/jcoyne/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/bundler/gems/hyrax-d5091b53bb71/app/services/hyrax/admin_set_service.rb:76:in `each'
     # /Users/jcoyne/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/bundler/gems/hyrax-d5091b53bb71/app/services/hyrax/admin_set_service.rb:76:in `block in count_files'
     # /Users/jcoyne/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/bundler/gems/hyrax-d5091b53bb71/app/services/hyrax/admin_set_service.rb:75:in `each'
     # /Users/jcoyne/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/bundler/gems/hyrax-d5091b53bb71/app/services/hyrax/admin_set_service.rb:75:in `count_files'
     # /Users/jcoyne/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/bundler/gems/hyrax-d5091b53bb71/app/services/hyrax/admin_set_service.rb:36:in `search_results_with_work_count'
     # /Users/jcoyne/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/bundler/gems/hyrax-d5091b53bb71/app/controllers/hyrax/admin_controller.rb:11:in `show'
```
Looks like a missing check for nil here: https://github.com/projecthydra-labs/hyrax/blob/master/app/services/hyrax/admin_set_service.rb#L77

**Comment by mjgiarlo** [comment]
@jcoyne How would one reproduce this?
