### ISSUE TITLE
Could not load the 'listen' gem

### ISSUE THREAD

**Issue by awead** [projecthydra-labs/hyrax#479]
### Descriptive summary

When following the install instructions, `rails new my_app -m https://raw.githubusercontent.com/projecthydra-labs/hyrax/master/template.rb`

I get:

```
    generate    hyrax:install
/Users/awead/.gem/ruby/2.3.1/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require': Could not load the 'listen' gem. Add `gem 'listen'` to the development group of your Gemfile (LoadError)
```

The app seems to build fine, so I don't know if this is a real issue or not.

**Comment by jcoyne** [comment]
@awead In hyku we don't have listen in the gemfile or Gemfile.lock. Try `--skip-listen` see https://github.com/cbeer/engine_cart/issues/62

**Comment by awead** [comment]
No effect if:
`ENGINE_CART_RAILS_OPTIONS="--skip_listen" bundle exec rails new ...`
Is there another method?

**Comment by jcoyne** [comment]
`rails new my_app --skip_listen -m https://raw.githubusercontent.com/projecthydra-labs/hyrax/master/template.rb`

**Comment by awead** [comment]
Yep. Just tried that, thanks!

**Comment by jcoyne** [comment]
The listen gem is causing nasty segfaults for me too:
```
       route  devise_for :users
/Users/jcoyne/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rb-fsevent-0.9.8/lib/rb-fsevent/fsevent.rb:106: [BUG] rb_gc_mark(): 0x007fbecb00eda8 is T_NONE
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/CrashReporter
     * /Library/Logs/CrashReporter
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   for more details.
Don't forget to include the above Crash Report log file in bug reports.

-- Control frame information -----------------------------------------------
c:0008 p:---- s:0032 e:000031 CFUNC  :new
c:0007 p:---- s:0029 e:000028 CFUNC  :popen
c:0006 p:0035 s:0024 e:000023 METHOD /Users/jcoyne/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rb-fsevent-0.9.8/lib/rb-fsevent/fsevent.rb:106
c:0005 p:0008 s:0020 e:000019 METHOD /Users/jcoyne/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rb-fsevent-0.9.8/lib/rb-fsevent/fsevent.rb:37
c:0004 p:0028 s:0014 e:000013 METHOD /Users/jcoyne/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/listen-3.0.8/lib/listen/adapter/darwin.rb:68
c:0003 p:0010 s:0009 e:000008 BLOCK  /Users/jcoyne/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/listen-3.0.8/lib/listen/adapter/darwin.rb:77 [FINISH]
c:0002 p:0009 s:0006 e:000005 BLOCK  /Users/jcoyne/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/listen-3.0.8/lib/listen/internals/thread_pool.rb:6 [FINISH]
c:0001 p:---- s:0003 e:000002 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/Users/jcoyne/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/listen-3.0.8/lib/listen/internals/thread_pool.rb:6:in `block in add'
/Users/jcoyne/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/listen-3.0.8/lib/listen/adapter/darwin.rb:77:in `block (2 levels) in _run_workers_in_background'
/Users/jcoyne/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/listen-3.0.8/lib/listen/adapter/darwin.rb:68:in `_run_worker'
/Users/jcoyne/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rb-fsevent-0.9.8/lib/rb-fsevent/fsevent.rb:37:in `run'
/Users/jcoyne/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rb-fsevent-0.9.8/lib/rb-fsevent/fsevent.rb:106:in `open_pipe'
/Users/jcoyne/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rb-fsevent-0.9.8/lib/rb-fsevent/fsevent.rb:106:in `popen'
/Users/jcoyne/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rb-fsevent-0.9.8/lib/rb-fsevent/fsevent.rb:106:in `new'

-- C level backtrace information -------------------------------------------
```

**Comment by jcoyne** [comment]
https://github.com/rails/rails/issues/26158
